#Logging config
LOG_DIR ="logs"
LOG_FILE="traffic.logs"

#City Signal config
CITY_SIGNAL_TRAFFIC_LIMIT=20
CITY_LOW_GREEN_TIME=30
CITY_HIGH_GREEN_TIME=60


#Highway signal config
HIGHWAY_HIGH_GREEN_TIME=30
HIGHWAY_LOW_GREEN_TIME=45
HIGHWAY_SIGNAL_TRAFFIC_LIMIT=90